package com.android.cglib.dx.b;

import android.support.v4.media.TransportMediator;
import android.widget.IPhotoView;
import com.android.cglib.dx.d.i;
import com.tencent.qq.widget.R;

public final class b {
    public static final a A = new a(22, "const-wide/16", com.android.cglib.dx.b.a.a.FORMAT_21S, a.NONE);
    public static final a B = new a(23, "const-wide/32", com.android.cglib.dx.b.a.a.FORMAT_31I, a.NONE);
    public static final a C = new a(24, "const-wide", com.android.cglib.dx.b.a.a.FORMAT_51L, a.NONE);
    public static final a D = new a(25, "const-wide/high16", com.android.cglib.dx.b.a.a.FORMAT_21H, a.NONE);
    public static final a E = new a(26, "const-string", com.android.cglib.dx.b.a.a.FORMAT_21C, a.STRING_REF);
    public static final a F = new a(27, "const-string/jumbo", com.android.cglib.dx.b.a.a.FORMAT_31C, a.STRING_REF);
    public static final a G = new a(28, "const-class", com.android.cglib.dx.b.a.a.FORMAT_21C, a.TYPE_REF);
    public static final a H = new a(29, "monitor-enter", com.android.cglib.dx.b.a.a.FORMAT_11X, a.NONE);
    public static final a I = new a(30, "monitor-exit", com.android.cglib.dx.b.a.a.FORMAT_11X, a.NONE);
    public static final a J = new a(31, "check-cast", com.android.cglib.dx.b.a.a.FORMAT_21C, a.TYPE_REF);
    public static final a K = new a(32, "instance-of", com.android.cglib.dx.b.a.a.FORMAT_22C, a.TYPE_REF);
    public static final a L = new a(33, "array-length", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a M = new a(34, "new-instance", com.android.cglib.dx.b.a.a.FORMAT_21C, a.TYPE_REF);
    public static final a N = new a(35, "new-array", com.android.cglib.dx.b.a.a.FORMAT_22C, a.TYPE_REF);
    public static final a O = new a(36, "filled-new-array", com.android.cglib.dx.b.a.a.FORMAT_35C, a.TYPE_REF);
    public static final a P = new a(37, "filled-new-array/range", com.android.cglib.dx.b.a.a.FORMAT_3RC, a.TYPE_REF);
    public static final a Q = new a(38, "fill-array-data", com.android.cglib.dx.b.a.a.FORMAT_31T, a.NONE);
    public static final a R = new a(39, "throw", com.android.cglib.dx.b.a.a.FORMAT_11X, a.NONE);
    public static final a S = new a(40, "goto", com.android.cglib.dx.b.a.a.FORMAT_10T, a.NONE);
    public static final a T = new a(41, "goto/16", com.android.cglib.dx.b.a.a.FORMAT_20T, a.NONE);
    public static final a U = new a(42, "goto/32", com.android.cglib.dx.b.a.a.FORMAT_30T, a.NONE);
    public static final a V = new a(43, "packed-switch", com.android.cglib.dx.b.a.a.FORMAT_31T, a.NONE);
    public static final a W = new a(44, "sparse-switch", com.android.cglib.dx.b.a.a.FORMAT_31T, a.NONE);
    public static final a X = new a(45, "cmpl-float", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a Y = new a(46, "cmpg-float", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a Z = new a(47, "cmpl-double", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a a = new a(-1, "<special>", com.android.cglib.dx.b.a.a.FORMAT_00X, a.NONE);
    public static final a aA = new a(80, "aput-char", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a aB = new a(81, "aput-short", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a aC = new a(82, "iget", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aD = new a(83, "iget-wide", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aE = new a(84, "iget-object", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aF = new a(85, "iget-boolean", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aG = new a(86, "iget-byte", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aH = new a(87, "iget-char", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aI = new a(88, "iget-short", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aJ = new a(89, "iput", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aK = new a(90, "iput-wide", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aL = new a(91, "iput-object", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aM = new a(92, "iput-boolean", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aN = new a(93, "iput-byte", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aO = new a(94, "iput-char", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aP = new a(95, "iput-short", com.android.cglib.dx.b.a.a.FORMAT_22C, a.FIELD_REF);
    public static final a aQ = new a(96, "sget", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a aR = new a(97, "sget-wide", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a aS = new a(98, "sget-object", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a aT = new a(99, "sget-boolean", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a aU = new a(100, "sget-byte", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a aV = new a(R.styleable.AppCompatTheme_autoCompleteTextViewStyle, "sget-char", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a aW = new a(R.styleable.AppCompatTheme_buttonStyle, "sget-short", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a aX = new a(R.styleable.AppCompatTheme_buttonStyleSmall, "sput", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a aY = new a(R.styleable.AppCompatTheme_checkboxStyle, "sput-wide", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a aZ = new a(R.styleable.AppCompatTheme_checkedTextViewStyle, "sput-object", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a aa = new a(48, "cmpg-double", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a ab = new a(49, "cmp-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a ac = new a(50, "if-eq", com.android.cglib.dx.b.a.a.FORMAT_22T, a.NONE);
    public static final a ad = new a(51, "if-ne", com.android.cglib.dx.b.a.a.FORMAT_22T, a.NONE);
    public static final a ae = new a(52, "if-lt", com.android.cglib.dx.b.a.a.FORMAT_22T, a.NONE);
    public static final a af = new a(53, "if-ge", com.android.cglib.dx.b.a.a.FORMAT_22T, a.NONE);
    public static final a ag = new a(54, "if-gt", com.android.cglib.dx.b.a.a.FORMAT_22T, a.NONE);
    public static final a ah = new a(55, "if-le", com.android.cglib.dx.b.a.a.FORMAT_22T, a.NONE);
    public static final a ai = new a(56, "if-eqz", com.android.cglib.dx.b.a.a.FORMAT_21T, a.NONE);
    public static final a aj = new a(57, "if-nez", com.android.cglib.dx.b.a.a.FORMAT_21T, a.NONE);
    public static final a ak = new a(58, "if-ltz", com.android.cglib.dx.b.a.a.FORMAT_21T, a.NONE);
    public static final a al = new a(59, "if-gez", com.android.cglib.dx.b.a.a.FORMAT_21T, a.NONE);
    public static final a am = new a(60, "if-gtz", com.android.cglib.dx.b.a.a.FORMAT_21T, a.NONE);
    public static final a an = new a(61, "if-lez", com.android.cglib.dx.b.a.a.FORMAT_21T, a.NONE);
    public static final a ao = new a(68, "aget", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a ap = new a(69, "aget-wide", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a aq = new a(70, "aget-object", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a ar = new a(71, "aget-boolean", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a as = new a(72, "aget-byte", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a at = new a(73, "aget-char", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a au = new a(74, "aget-short", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a av = new a(75, "aput", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a aw = new a(76, "aput-wide", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a ax = new a(77, "aput-object", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a ay = new a(78, "aput-boolean", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a az = new a(79, "aput-byte", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a b = new a(256, "packed-switch-payload", com.android.cglib.dx.b.a.a.FORMAT_PACKED_SWITCH_PAYLOAD, a.NONE);
    public static final a bA = new a(135, "float-to-int", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bB = new a(136, "float-to-long", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bC = new a(137, "float-to-double", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bD = new a(138, "double-to-int", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bE = new a(139, "double-to-long", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bF = new a(140, "double-to-float", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bG = new a(141, "int-to-byte", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bH = new a(142, "int-to-char", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bI = new a(143, "int-to-short", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bJ = new a(144, "add-int", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bK = new a(145, "sub-int", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bL = new a(146, "mul-int", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bM = new a(147, "div-int", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bN = new a(148, "rem-int", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bO = new a(149, "and-int", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bP = new a(150, "or-int", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bQ = new a(151, "xor-int", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bR = new a(152, "shl-int", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bS = new a(153, "shr-int", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bT = new a(154, "ushr-int", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bU = new a(155, "add-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bV = new a(156, "sub-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bW = new a(157, "mul-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bX = new a(158, "div-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bY = new a(159, "rem-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a bZ = new a(160, "and-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a ba = new a(R.styleable.AppCompatTheme_editTextStyle, "sput-boolean", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a bb = new a(R.styleable.AppCompatTheme_radioButtonStyle, "sput-byte", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a bc = new a(R.styleable.AppCompatTheme_ratingBarStyle, "sput-char", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a bd = new a(R.styleable.AppCompatTheme_ratingBarStyleIndicator, "sput-short", com.android.cglib.dx.b.a.a.FORMAT_21C, a.FIELD_REF);
    public static final a be = new a(R.styleable.AppCompatTheme_ratingBarStyleSmall, "invoke-virtual", com.android.cglib.dx.b.a.a.FORMAT_35C, a.METHOD_REF);
    public static final a bf = new a(R.styleable.AppCompatTheme_seekBarStyle, "invoke-super", com.android.cglib.dx.b.a.a.FORMAT_35C, a.METHOD_REF);
    public static final a bg = new a(R.styleable.AppCompatTheme_spinnerStyle, "invoke-direct", com.android.cglib.dx.b.a.a.FORMAT_35C, a.METHOD_REF);
    public static final a bh = new a(R.styleable.AppCompatTheme_switchStyle, "invoke-static", com.android.cglib.dx.b.a.a.FORMAT_35C, a.METHOD_REF);
    public static final a bi = new a(R.styleable.AppCompatTheme_listMenuViewStyle, "invoke-interface", com.android.cglib.dx.b.a.a.FORMAT_35C, a.METHOD_REF);
    public static final a bj = new a(116, "invoke-virtual/range", com.android.cglib.dx.b.a.a.FORMAT_3RC, a.METHOD_REF);
    public static final a bk = new a(117, "invoke-super/range", com.android.cglib.dx.b.a.a.FORMAT_3RC, a.METHOD_REF);
    public static final a bl = new a(118, "invoke-direct/range", com.android.cglib.dx.b.a.a.FORMAT_3RC, a.METHOD_REF);
    public static final a bm = new a(119, "invoke-static/range", com.android.cglib.dx.b.a.a.FORMAT_3RC, a.METHOD_REF);
    public static final a bn = new a(120, "invoke-interface/range", com.android.cglib.dx.b.a.a.FORMAT_3RC, a.METHOD_REF);
    public static final a bo = new a(123, "neg-int", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bp = new a(124, "not-int", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bq = new a(125, "neg-long", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a br = new a(TransportMediator.KEYCODE_MEDIA_PLAY, "not-long", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bs = new a(TransportMediator.KEYCODE_MEDIA_PAUSE, "neg-float", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bt = new a(128, "neg-double", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bu = new a(129, "int-to-long", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bv = new a(TransportMediator.KEYCODE_MEDIA_RECORD, "int-to-float", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bw = new a(131, "int-to-double", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bx = new a(132, "long-to-int", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a by = new a(133, "long-to-float", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a bz = new a(134, "long-to-double", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a c = new a(512, "sparse-switch-payload", com.android.cglib.dx.b.a.a.FORMAT_SPARSE_SWITCH_PAYLOAD, a.NONE);
    public static final a cA = new a(187, "add-long/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cB = new a(188, "sub-long/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cC = new a(189, "mul-long/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cD = new a(190, "div-long/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cE = new a(191, "rem-long/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cF = new a(192, "and-long/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cG = new a(193, "or-long/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cH = new a(194, "xor-long/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cI = new a(195, "shl-long/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cJ = new a(196, "shr-long/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cK = new a(197, "ushr-long/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cL = new a(198, "add-float/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cM = new a(199, "sub-float/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cN = new a(IPhotoView.DEFAULT_ZOOM_DURATION, "mul-float/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cO = new a(201, "div-float/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cP = new a(202, "rem-float/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cQ = new a(203, "add-double/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cR = new a(204, "sub-double/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cS = new a(205, "mul-double/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cT = new a(206, "div-double/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cU = new a(207, "rem-double/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cV = new a(208, "add-int/lit16", com.android.cglib.dx.b.a.a.FORMAT_22S, a.NONE);
    public static final a cW = new a(209, "rsub-int", com.android.cglib.dx.b.a.a.FORMAT_22S, a.NONE);
    public static final a cX = new a(210, "mul-int/lit16", com.android.cglib.dx.b.a.a.FORMAT_22S, a.NONE);
    public static final a cY = new a(211, "div-int/lit16", com.android.cglib.dx.b.a.a.FORMAT_22S, a.NONE);
    public static final a cZ = new a(212, "rem-int/lit16", com.android.cglib.dx.b.a.a.FORMAT_22S, a.NONE);
    public static final a ca = new a(161, "or-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a cb = new a(162, "xor-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a cc = new a(163, "shl-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a cd = new a(164, "shr-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a ce = new a(165, "ushr-long", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a cf = new a(166, "add-float", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a cg = new a(167, "sub-float", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a ch = new a(168, "mul-float", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a ci = new a(169, "div-float", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a cj = new a(170, "rem-float", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a ck = new a(171, "add-double", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a cl = new a(172, "sub-double", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a cm = new a(173, "mul-double", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a cn = new a(174, "div-double", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a co = new a(175, "rem-double", com.android.cglib.dx.b.a.a.FORMAT_23X, a.NONE);
    public static final a cp = new a(176, "add-int/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cq = new a(177, "sub-int/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cr = new a(178, "mul-int/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cs = new a(179, "div-int/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a ct = new a(180, "rem-int/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cu = new a(181, "and-int/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cv = new a(182, "or-int/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cw = new a(183, "xor-int/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cx = new a(184, "shl-int/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cy = new a(185, "shr-int/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a cz = new a(186, "ushr-int/2addr", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a d = new a(768, "fill-array-data-payload", com.android.cglib.dx.b.a.a.FORMAT_FILL_ARRAY_DATA_PAYLOAD, a.NONE);
    public static final a dA = new a(3327, "iget-short/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dB = new a(3583, "iput/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dC = new a(3839, "iput-wide/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dD = new a(4095, "iput-object/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dE = new a(4351, "iput-boolean/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dF = new a(4607, "iput-byte/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dG = new a(4863, "iput-char/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dH = new a(5119, "iput-short/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dI = new a(5375, "sget/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dJ = new a(5631, "sget-wide/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dK = new a(5887, "sget-object/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dL = new a(6143, "sget-boolean/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dM = new a(6399, "sget-byte/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dN = new a(6655, "sget-char/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dO = new a(6911, "sget-short/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dP = new a(7167, "sput/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dQ = new a(7423, "sput-wide/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dR = new a(7679, "sput-object/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dS = new a(7935, "sput-boolean/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dT = new a(8191, "sput-byte/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dU = new a(8447, "sput-char/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dV = new a(8703, "sput-short/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.FIELD_REF);
    public static final a dW = new a(8959, "invoke-virtual/jumbo", com.android.cglib.dx.b.a.a.FORMAT_5RC, a.METHOD_REF);
    public static final a dX = new a(9215, "invoke-super/jumbo", com.android.cglib.dx.b.a.a.FORMAT_5RC, a.METHOD_REF);
    public static final a dY = new a(9471, "invoke-direct/jumbo", com.android.cglib.dx.b.a.a.FORMAT_5RC, a.METHOD_REF);
    public static final a dZ = new a(9727, "invoke-static/jumbo", com.android.cglib.dx.b.a.a.FORMAT_5RC, a.METHOD_REF);
    public static final a da = new a(213, "and-int/lit16", com.android.cglib.dx.b.a.a.FORMAT_22S, a.NONE);
    public static final a db = new a(214, "or-int/lit16", com.android.cglib.dx.b.a.a.FORMAT_22S, a.NONE);
    public static final a dc = new a(215, "xor-int/lit16", com.android.cglib.dx.b.a.a.FORMAT_22S, a.NONE);
    public static final a dd = new a(216, "add-int/lit8", com.android.cglib.dx.b.a.a.FORMAT_22B, a.NONE);
    public static final a de = new a(217, "rsub-int/lit8", com.android.cglib.dx.b.a.a.FORMAT_22B, a.NONE);
    public static final a df = new a(218, "mul-int/lit8", com.android.cglib.dx.b.a.a.FORMAT_22B, a.NONE);
    public static final a dg = new a(219, "div-int/lit8", com.android.cglib.dx.b.a.a.FORMAT_22B, a.NONE);
    public static final a dh = new a(220, "rem-int/lit8", com.android.cglib.dx.b.a.a.FORMAT_22B, a.NONE);
    public static final a di = new a(221, "and-int/lit8", com.android.cglib.dx.b.a.a.FORMAT_22B, a.NONE);
    public static final a dj = new a(222, "or-int/lit8", com.android.cglib.dx.b.a.a.FORMAT_22B, a.NONE);
    public static final a dk = new a(223, "xor-int/lit8", com.android.cglib.dx.b.a.a.FORMAT_22B, a.NONE);
    public static final a dl = new a(224, "shl-int/lit8", com.android.cglib.dx.b.a.a.FORMAT_22B, a.NONE);
    public static final a dm = new a(225, "shr-int/lit8", com.android.cglib.dx.b.a.a.FORMAT_22B, a.NONE);
    public static final a dn = new a(226, "ushr-int/lit8", com.android.cglib.dx.b.a.a.FORMAT_22B, a.NONE);

    /* renamed from: do  reason: not valid java name */
    public static final a f1do = new a(255, "const-class/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.TYPE_REF);
    public static final a dp = new a(511, "check-cast/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.TYPE_REF);
    public static final a dq = new a(767, "instance-of/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.TYPE_REF);
    public static final a dr = new a(1023, "new-instance/jumbo", com.android.cglib.dx.b.a.a.FORMAT_41C, a.TYPE_REF);
    public static final a ds = new a(1279, "new-array/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.TYPE_REF);
    public static final a dt = new a(1535, "filled-new-array/jumbo", com.android.cglib.dx.b.a.a.FORMAT_5RC, a.TYPE_REF);
    public static final a du = new a(1791, "iget/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dv = new a(2047, "iget-wide/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dw = new a(2303, "iget-object/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dx = new a(2559, "iget-boolean/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dy = new a(2815, "iget-byte/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a dz = new a(3071, "iget-char/jumbo", com.android.cglib.dx.b.a.a.FORMAT_52C, a.FIELD_REF);
    public static final a e = new a(0, "nop", com.android.cglib.dx.b.a.a.FORMAT_10X, a.NONE);
    public static final a ea = new a(9983, "invoke-interface/jumbo", com.android.cglib.dx.b.a.a.FORMAT_5RC, a.METHOD_REF);
    private static final a[] eb = new a[65537];
    public static final a f = new a(1, "move", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a g = new a(2, "move/from16", com.android.cglib.dx.b.a.a.FORMAT_22X, a.NONE);
    public static final a h = new a(3, "move/16", com.android.cglib.dx.b.a.a.FORMAT_32X, a.NONE);
    public static final a i = new a(4, "move-wide", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a j = new a(5, "move-wide/from16", com.android.cglib.dx.b.a.a.FORMAT_22X, a.NONE);
    public static final a k = new a(6, "move-wide/16", com.android.cglib.dx.b.a.a.FORMAT_32X, a.NONE);
    public static final a l = new a(7, "move-object", com.android.cglib.dx.b.a.a.FORMAT_12X, a.NONE);
    public static final a m = new a(8, "move-object/from16", com.android.cglib.dx.b.a.a.FORMAT_22X, a.NONE);
    public static final a n = new a(9, "move-object/16", com.android.cglib.dx.b.a.a.FORMAT_32X, a.NONE);
    public static final a o = new a(10, "move-result", com.android.cglib.dx.b.a.a.FORMAT_11X, a.NONE);
    public static final a p = new a(11, "move-result-wide", com.android.cglib.dx.b.a.a.FORMAT_11X, a.NONE);

    /* renamed from: q  reason: collision with root package name */
    public static final a f15q = new a(12, "move-result-object", com.android.cglib.dx.b.a.a.FORMAT_11X, a.NONE);
    public static final a r = new a(13, "move-exception", com.android.cglib.dx.b.a.a.FORMAT_11X, a.NONE);
    public static final a s = new a(14, "return-void", com.android.cglib.dx.b.a.a.FORMAT_10X, a.NONE);
    public static final a t = new a(15, "return", com.android.cglib.dx.b.a.a.FORMAT_11X, a.NONE);
    public static final a u = new a(16, "return-wide", com.android.cglib.dx.b.a.a.FORMAT_11X, a.NONE);
    public static final a v = new a(17, "return-object", com.android.cglib.dx.b.a.a.FORMAT_11X, a.NONE);
    public static final a w = new a(18, "const/4", com.android.cglib.dx.b.a.a.FORMAT_11N, a.NONE);
    public static final a x = new a(19, "const/16", com.android.cglib.dx.b.a.a.FORMAT_21S, a.NONE);
    public static final a y = new a(20, "const", com.android.cglib.dx.b.a.a.FORMAT_31I, a.NONE);
    public static final a z = new a(21, "const/high16", com.android.cglib.dx.b.a.a.FORMAT_21H, a.NONE);

    public static class a {
        private final int a;
        private final String b;
        private final com.android.cglib.dx.b.a.a c;
        private final a d;

        public a(int i, String str, com.android.cglib.dx.b.a.a aVar, a aVar2) {
            this.a = i;
            this.b = str;
            this.c = aVar;
            this.d = aVar2;
        }

        public int a() {
            return this.a;
        }

        public String b() {
            return this.b;
        }
    }

    static {
        a(a);
        a(b);
        a(c);
        a(d);
        a(e);
        a(f);
        a(g);
        a(h);
        a(i);
        a(j);
        a(k);
        a(l);
        a(m);
        a(n);
        a(o);
        a(p);
        a(f15q);
        a(r);
        a(s);
        a(t);
        a(u);
        a(v);
        a(w);
        a(x);
        a(y);
        a(z);
        a(A);
        a(B);
        a(C);
        a(D);
        a(E);
        a(F);
        a(G);
        a(H);
        a(I);
        a(J);
        a(K);
        a(L);
        a(M);
        a(N);
        a(O);
        a(P);
        a(Q);
        a(R);
        a(S);
        a(T);
        a(U);
        a(V);
        a(W);
        a(X);
        a(Y);
        a(Z);
        a(aa);
        a(ab);
        a(ac);
        a(ad);
        a(ae);
        a(af);
        a(ag);
        a(ah);
        a(ai);
        a(aj);
        a(ak);
        a(al);
        a(am);
        a(an);
        a(ao);
        a(ap);
        a(aq);
        a(ar);
        a(as);
        a(at);
        a(au);
        a(av);
        a(aw);
        a(ax);
        a(ay);
        a(az);
        a(aA);
        a(aB);
        a(aC);
        a(aD);
        a(aE);
        a(aF);
        a(aG);
        a(aH);
        a(aI);
        a(aJ);
        a(aK);
        a(aL);
        a(aM);
        a(aN);
        a(aO);
        a(aP);
        a(aQ);
        a(aR);
        a(aS);
        a(aT);
        a(aU);
        a(aV);
        a(aW);
        a(aX);
        a(aY);
        a(aZ);
        a(ba);
        a(bb);
        a(bc);
        a(bd);
        a(be);
        a(bf);
        a(bg);
        a(bh);
        a(bi);
        a(bj);
        a(bk);
        a(bl);
        a(bm);
        a(bn);
        a(bo);
        a(bp);
        a(bq);
        a(br);
        a(bs);
        a(bt);
        a(bu);
        a(bv);
        a(bw);
        a(bx);
        a(by);
        a(bz);
        a(bA);
        a(bB);
        a(bC);
        a(bD);
        a(bE);
        a(bF);
        a(bG);
        a(bH);
        a(bI);
        a(bJ);
        a(bK);
        a(bL);
        a(bM);
        a(bN);
        a(bO);
        a(bP);
        a(bQ);
        a(bR);
        a(bS);
        a(bT);
        a(bU);
        a(bV);
        a(bW);
        a(bX);
        a(bY);
        a(bZ);
        a(ca);
        a(cb);
        a(cc);
        a(cd);
        a(ce);
        a(cf);
        a(cg);
        a(ch);
        a(ci);
        a(cj);
        a(ck);
        a(cl);
        a(cm);
        a(cn);
        a(co);
        a(cp);
        a(cq);
        a(cr);
        a(cs);
        a(ct);
        a(cu);
        a(cv);
        a(cw);
        a(cx);
        a(cy);
        a(cz);
        a(cA);
        a(cB);
        a(cC);
        a(cD);
        a(cE);
        a(cF);
        a(cG);
        a(cH);
        a(cI);
        a(cJ);
        a(cK);
        a(cL);
        a(cM);
        a(cN);
        a(cO);
        a(cP);
        a(cQ);
        a(cR);
        a(cS);
        a(cT);
        a(cU);
        a(cV);
        a(cW);
        a(cX);
        a(cY);
        a(cZ);
        a(da);
        a(db);
        a(dc);
        a(dd);
        a(de);
        a(df);
        a(dg);
        a(dh);
        a(di);
        a(dj);
        a(dk);
        a(dl);
        a(dm);
        a(dn);
        a(f1do);
        a(dp);
        a(dq);
        a(dr);
        a(ds);
        a(dt);
        a(du);
        a(dv);
        a(dw);
        a(dx);
        a(dy);
        a(dz);
        a(dA);
        a(dB);
        a(dC);
        a(dD);
        a(dE);
        a(dF);
        a(dG);
        a(dH);
        a(dI);
        a(dJ);
        a(dK);
        a(dL);
        a(dM);
        a(dN);
        a(dO);
        a(dP);
        a(dQ);
        a(dR);
        a(dS);
        a(dT);
        a(dU);
        a(dV);
        a(dW);
        a(dX);
        a(dY);
        a(dZ);
        a(ea);
    }

    public static a a(int i2) {
        try {
            a aVar = eb[i2 + 1];
            if (aVar != null) {
                return aVar;
            }
        } catch (ArrayIndexOutOfBoundsException unused) {
        }
        throw new IllegalArgumentException("bogus opcode: " + i.d(i2));
    }

    private static void a(a aVar) {
        eb[aVar.a() + 1] = aVar;
    }

    public static String b(int i2) {
        return a(i2).b();
    }
}
